name: build and test
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: set up repo
              uses: actions/checkout@main
              with:
                  ref: master
            - name: setup nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"
            - name: install packages
              run: npm ci
            - name: check scripts
              run: npm run
            - name: build
              run: npm run build
            - name: test
              run: npm test
